topic_cmd_vel = "trilobot/cmd_vel"
topic_sonar_data = "trilobot/sonar_data"
topic_battery_raw = "trilobot/battery_raw"
topic_battery = "trilobot/battery"
topic_trilobot_odometry = "trilobot/odometry"
topic_rosserial_start = "trilobot/rosserial_start"
topic_need_charge = "trilobot/need_charge"
topic_charging = "trilobot/charging"